pushd "%~dp0"

set CHESSCOACH_DATA=%localappdata%\ChessCoach
set CHESSCOACH_GAMES_SUPERVISED=%CHESSCOACH_DATA%\Games\Supervised
set CHESSCOACH_GAMES_VALIDATION=%CHESSCOACH_DATA%\Games\Validation
set CHESSCOACH_DATA_DATA=%CHESSCOACH_DATA%\Data
set CHESSCOACH_BZ2=%CHESSCOACH_DATA%\bzip2
set CHESSCOACH_BZ2_ZIP=%CHESSCOACH_DATA%\bzip2-1.0.8.0-win-x64.zip
set CHESSCOACH_BZ2_EXE=%CHESSCOACH_BZ2%\bzip2.exe
set CHESSCOACH_VALIDATION_DATA_BZ2=%CHESSCOACH_DATA%\ccrl-pgn.tar.bz2
set CHESSCOACH_VALIDATION_DATA_TAR=%CHESSCOACH_DATA%\ccrl-pgn.tar
set CHESSCOACH_VALIDATION_DATA_CCRL=%CHESSCOACH_DATA_DATA%\cclr
set CHESSCOACH_VALIDATION_DATA_CCRL_TRAINING=%CHESSCOACH_VALIDATION_DATA_CCRL%\train
set CHESSCOACH_VALIDATION_DATA_CCRL_VALIDATION=%CHESSCOACH_VALIDATION_DATA_CCRL%\test

mkdir "%CHESSCOACH_GAMES_SUPERVISED%"
mkdir "%CHESSCOACH_GAMES_VALIDATION%"
mkdir "%CHESSCOACH_DATA_DATA%"
mkdir "%CHESSCOACH_BZ2%"

curl -L https://github.com/philr/bzip2-windows/releases/download/v1.0.8.0/bzip2-1.0.8.0-win-x64.zip -o "%CHESSCOACH_BZ2_ZIP%"
tar -x -f "%CHESSCOACH_BZ2_ZIP%" -C "%CHESSCOACH_BZ2%"

curl -L https://storage.lczero.org/files/ccrl-pgn.tar.bz2 -o "%CHESSCOACH_VALIDATION_DATA_BZ2%"
"%CHESSCOACH_BZ2_EXE%" -d "%CHESSCOACH_VALIDATION_DATA_BZ2%"

tar -x -f "%CHESSCOACH_VALIDATION_DATA_TAR%" -C "%CHESSCOACH_DATA_DATA%"

..\cpp\x64\Release\ChessCoachPgnToGames.exe -i "%CHESSCOACH_VALIDATION_DATA_CCRL_TRAINING%" -o "%CHESSCOACH_GAMES_SUPERVISED%"
..\cpp\x64\Release\ChessCoachPgnToGames.exe -i "%CHESSCOACH_VALIDATION_DATA_CCRL_VALIDATION%" -o "%CHESSCOACH_GAMES_VALIDATION%"

del "%CHESSCOACH_BZ2_ZIP%"
rmdir /s /q "%CHESSCOACH_BZ2%"
del "%CHESSCOACH_VALIDATION_DATA_BZ2%"
del "%CHESSCOACH_VALIDATION_DATA_TAR%"
rmdir /s /q "%CHESSCOACH_VALIDATION_DATA_CCRL%"

popd